// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BigStarLib.Models;

public partial class Alien
{
    public int CardId { get; set; }

    public int FamilyId { get; set; }

    public string FavoriteEarthFood { get; set; }

    public string Locomotion { get; set; }

    public string DreamJob { get; set; }

    public string Planet { get; set; }

    public virtual CollectibleCard Card { get; set; }

    public virtual CollectibleCard Family { get; set; }
}