// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BigStarLib.Models;

public partial class CardFamily
{
    public int FamilyId { get; set; }

    public string FamilyType { get; set; }

    public virtual ICollection<CollectibleCard> CollectibleCards { get; set; } = new List<CollectibleCard>();
}