// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BigStarLib.Models;

public partial class CollectibleCard
{
    public int CardId { get; set; }

    public int FamilyId { get; set; }

    public string CardName { get; set; }

    public string Slogan { get; set; }

    public double? CatalogPrice { get; set; }

    public double? BidPrice { get; set; }

    public string ImageName { get; set; }

    public string Description { get; set; }

    public int? PopularityRank { get; set; }

    public string TeamName { get; set; }

    public int? EyeCount { get; set; }

    public virtual Alien AlienCard { get; set; }

    public virtual ICollection<Alien> AlienFamilies { get; set; } = new List<Alien>();

    public virtual CardFamily Family { get; set; }

    public virtual Monster MonsterCard { get; set; }

    public virtual ICollection<Monster> MonsterFamilies { get; set; } = new List<Monster>();

    public virtual Team TeamNameNavigation { get; set; }
}