// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BigStarLib.Models;

public partial class Monster
{
    public int CardId { get; set; }

    public int FamilyId { get; set; }

    public bool Antenna { get; set; }

    public bool Spikes { get; set; }

    public virtual CollectibleCard Card { get; set; }

    public virtual CollectibleCard Family { get; set; }
}