// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BigStarLib.Models;

public partial class Robot
{
    public int Id { get; set; }
}