// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToursLib.Models;

public partial class Testimonial
{
    public int TestimonialId { get; set; }

    public string CustomerName { get; set; }

    public string Comment { get; set; }
}