// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToursLib.Models;

public partial class Tour
{
    public int TourId { get; set; }

    public string TourName { get; set; }

    public bool? SeniorDiscountAvailable { get; set; }

    public bool? KidFriendly { get; set; }

    public bool? MultiDay { get; set; }

    public string Region { get; set; }

    public int? MaxPeoplePerTour { get; set; }

    public string TourImagePath { get; set; }

    public string Description { get; set; }
}