// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToursLib.Models;

public partial class TravelTip
{
    public int TipId { get; set; }

    public string Headline { get; set; }

    public string TipText { get; set; }
}